### ISSUE TITLE
Unable to use SAML

### ISSUE THREAD

**Issue by mike240se** [boschkundendienst/guacamole-docker-compose#90] opened 2024-03-09 16:47 UTC
Wondering if anyone has found a solution to the strict requirements for SAML?   I dont want to disable them as it says you should never disable in a PROD enviroment but this is the error I get:

`guacamole_compose           | 01:17:46.818 [http-nio-8080-exec-9] ERROR c.onelogin.saml2.authn.SamlResponse - The response was received at http://guacamole:8080/guacamole/api/ext/saml/callback instead of https://guactest.MYPUBLICDOMAIN.org:8443/api/ext/saml/callback`

It seems to be an issue of using the nginx reverse proxy in a docker environment, its not really an issue with this compose obviously, but thinking others using it have run into the same probleem.  Thanks.

**Comment by boschkundendienst** [comment] 2024-03-12 18:02
Hi, thanks for your info. I would suggest you start from scratch or remove my nginx configuration from your docker setup and create your personal nginx in front to setup things the way you would them to be in your environment.
Anyways since this is not a bug or something I will fix I will close this issue now.
Greets Peter

**Closed by boschkundendienst** 2024-03-12 18:02 UTC
