### ISSUE TITLE
Cannot connect to any machine outside of localhost

### ISSUE THREAD

**Issue by konika3** [boschkundendienst/guacamole-docker-compose#42] opened 2022-09-14 20:52 UTC
Hi,

I am having issues connecting to any machine (via RDP, SSH, VNC) outside of the Ubuntu machine that I installed this guacamole docker container on. They are all on the same subnet and can verify that I can ping and SSH into the hosts from within the guacd_compose and guacamole_compose containers.

I'm not running any firewalls on any of the machines. In fact, the remote machines are fresh, vanilla installs of Ubuntu and Windows for the purposes of testing Guacamole for a project. RDP is enabled on Windows and can connect to it via RDP client on another machine running on the same subnet.

In the connection settings, do I need to fill out any information under the 'Guacamole Proxy Paramters (GUACD)' section? I tried 'guacd' as the hostname as it is referenced in the docker-compose.yml file, but still am getting the same error.

Any support would be greatly appreciated! Thank you!

guacamole HTTP interface error when connecting to any remote host (other than localhost):
```
An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs. Reconnecting in 6 seconds...'
```

guacamole_compose logs:
```
Exception in thread "Thread-34" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
20:43:08.586 [http-nio-8080-exec-6] INFO  o.a.g.tunnel.TunnelRequestService - User "guacadmin" disconnected from connection "1". Duration: 74 milliseconds
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:442)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:314)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:254)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:195)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
20:43:14.999 [http-nio-8080-exec-3] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Creation of WebSocket tunnel to guacd failed: java.net.ConnectException: Connection refused (Connection refused)
```

guacd_compose logs:
```
guacd[7]: INFO: Connection ID is "$208014e1-862f-4118-8b35-8d275fce7886"
guacd[184]: INFO:       User "@a9bf3404-b84c-4eb9-90d0-30ae30cb8022" joined connection "$208014e1-862f-4118-8b35-8d275fce7886" (1 users now present)
guacd[184]: ERROR:      Unable to connect to any addresses.
guacd[184]: INFO:       User "@a9bf3404-b84c-4eb9-90d0-30ae30cb8022" disconnected (0 users remain)
guacd[184]: INFO:       Last user of connection "$208014e1-862f-4118-8b35-8d275fce7886" disconnected
guacd[7]: INFO: Connection "$208014e1-862f-4118-8b35-8d275fce7886" removed.
```

**Comment by boschkundendienst** [comment] 2022-09-15 15:37
Hi, thanks for your comment. It seems, that the problem is not related to this repository. The problems seems to be related to your docker installation or configuration. I had a user with similar issues (on a MAC) and he uninstalled, then re-installed docker/docker-desktop software and it was working then.

Problems must be related to your docker network device(s) especially the one(s) used for bridging. Since I use the "bridge" network driver in the docker-compose.yml file the problem must be with the underlying docker internal bridging.

There are also many troubleshooting guides online for the subject "docker container cannot connect to outside".

I will close this issue but feel free to update if you found the problem since it might be helpful to others.

**Comment by cHunter789** [comment] 2022-09-15 16:10
Hi, I start to using your compose, THX for great point to start. One notice from me is that, **the most of WiFi drivers DO NOT support bridge mode.** Worth to add some notice for a notebook users ;)

**Comment by konika3** [comment] 2022-09-15 18:13
> There are also many troubleshooting guides online for the subject "docker container cannot connect to outside".

Thank you for the response. I can confirm that I can connect to outside devices from within each of the guacamole containers. If I "docker exec" into the containers, I can ping outside devices, and even telnet into ports 22, 5900, and 3389 to verify that the remote devices are listening (even though they usually give garbled responses since using telnet).

When adding a new connection within the Guacamole UI, is anything required to be added to the Guacamole Proxy Paramters (GUACD)' section? I have been trying to think if there's a comms issue between the 'guacamole_compose' and 'guacd_compose' containers?

> I had a user with similar issues (on a MAC) and he uninstalled, then re-installed docker/docker-desktop software and it was working then.

I tried on three different OS's. Ubuntu 22.04, 20.04 and Debian.

**Closed** 2023-02-04 18:44 UTC

**Comment by gbajson** [comment] 2023-02-25 20:16
Hi,
I experience similar issue with VNC connection. 

I can manually connect to VNC server from within `guacamole_compose` container, but I see the errors in logs:

**Investigation:**
```
$ docker cp ~/Downloads/busybox guacamole_compose:/tmp
$ docker exec -ti guacamole_compose /bin/bash
guacamole@43f04b98ba7f:/opt/guacamole$ /tmp/busybox nc 10.144.107.99 5900
RFB 003.008
```

**Logs:**
```
Exception in thread "Thread-131" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:442)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:314)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:254)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:195)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
```

I use Ubuntu 22.04 with standard docker-ce network configuration.
